image: golang:10.1

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - test
  - build

before_script:
  - sudo apt install golang
  - export GOROOT="/usr/lib/go"
  - export GOPATH="/gopath"
  - export GOBIN="/gopath/bin"
  - export PATH="$PATH:$GOROOT/bin:$GOPATH/bin"
  - go get -u github.com/golang/dep/cmd/dep
  - mkdir -p $GOPATH/src
  - cd $GOPATH/src
  - ln -s $CI_PROJECT_DIR
  - cd $CI_PROJECT_NAME
  - dep ensure

#unit_tests:
#  stage: test
#  script:
#    - make test


style:
  stage: test
  script:
    - make style
    
format:
  stage: test
  script:
    - make format
    
vet:
  stage: test
  script:
    - make vet

build:
  stage: build
  script:
    - make build

docker:
  stage: build
  script:
    - make docker
