image: golang:latest




cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - build
  - test
  - release

variables:
  CONTAINER_TEST_IMAGE: docker.tsi-dev.otc-service.com/tsi-automation/inspec_exporter:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: docker.tsi-dev.otc-service.com/tsi-automation/inspec_exporter:latest

before_script:
#  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.tsi-dev.otc-service.com
  - mkdir -p $GOPATH/src/gitlab.tsi-dev.otc-service.com
  - cd $GOPATH/src/gitlab.tsi-dev.otc-service.com
  - ln -s $CI_PROJECT_DIR
  - cd $CI_PROJECT_NAME
  - pwd

#test:
#  stage: test
#  script:
#    - make test

style:
  stage: build
  script:
    - make style
    
format:
  stage: build
  script:
    - make format

build:
  stage: build
  script:
    - make build
#    - docker build -t $CONTAINER_TEST_IMAGE .
#    - docker push $CONTAINER_TEST_IMAGE
  artifacts:
    paths:
    - inspec_exporter
    expire_in: 1 week

release-image:
  image: docker:latest
  services:
    - docker:dind
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
