image: golang:1.10

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - test
  - build

#before_script:
#  - mkdir -p /go/src/gitlab.com/tsi-automation /go/src/_/builds
#  - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/tsi-automation/inspec_exporter
#  - ln -s /go/src/gitlab.com/tsi-automation /go/src/_/builds/tsi-automation
#  - make dep

#unit_tests:
#  stage: test
#  script:
#    - make test


style:
  stage: test
  script:
    - make style
    
format:
  stage: test
  script:
    - make format
    
vet:
  stage: test
  script:
    - make vet

build:
  stage: build
  script:
    - make build

docker:
  stage: build
  script:
    - make docker
