image: golang:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - /go/src/gitlab.tsi-dev.otc-service.com/tsi-automation/inspec_exporter/vendor/github.com
    - /go/src/gitlab.tsi-dev.otc-service.com/tsi-automation/inspec_exporter/vendor/golang.org
    - /go/src/gitlab.tsi-dev.otc-service.com/tsi-automation/inspec_exporter/vendor/gopkg.in
    - inspec_exporter

stages:
  - build
  - test
  - release

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: docker.tsi-dev.otc-service.com/tsi-automation/inspec_exporter:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: docker.tsi-dev.otc-service.com/tsi-automation/inspec_exporter:latest

before_script:
  - mkdir -p $GOPATH/src/gitlab.tsi-dev.otc-service.com/tsi-automation
  - cd $GOPATH/src/gitlab.tsi-dev.otc-service.com/tsi-automation
  - ln -s $CI_PROJECT_DIR
  - cd $CI_PROJECT_NAME

#test:
#  stage: test
#  script:
#    - make test

style:
  stage: build
  script:
    - make style
    
format:
  stage: build
  script:
    - make format

build:
  stage: build
  script:
    - make build
  artifacts:
    paths:
    - inspec_exporter
    expire_in: 1 week

release-image:
  image: docker:latest
  services:
    - docker:dind
  stage: release
  script:
    - cp inspec.yml.dest inspec.yml
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.tsi-dev.otc-service.com
    - make docker
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
