[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "github.com/kennygrant/sanitize"
  version = "1.2.4"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.1"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.1"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.6"

[prune]
  go-tests = true
  unused-packages = true
